CREATE TABLE contratante(
	codigo SERIAL PRIMARY KEY,	
	nome VARCHAR(50) NOT NULL,
	cpf VARCHAR(11) NOT NULL,
	telefone VARCHAR(11) NOT NULL,
	estado VARCHAR(50) NOT NULL,
	cidade VARCHAR(50) NOT NULL,
	bairro VARCHAR(50) NOT NULL,
	rua VARCHAR(50) NOT NULL,
	numero_casa INTEGER,
	UNIQUE(cpf)
);